Repository DBrueberg/ZombieWar, pull requests merged in 2021-12, with the labels that each got.

#19 Formatting and Minimum Characters
  src/entity/CharacterList.java
  src/entity/Report.java
Labels: enhancement

#20 Pulled off #19 before merge. Changed Match algorithm, added comments,…
  src/control/PlayMatchControl.java
  src/entity/Match.java
Labels: bug

#21 Version 1 Release
  README.txt
  src/ZombieWar.java
  src/control/EndGameControl.java
  src/control/GameControl.java
  src/control/PlayMatchControl.java
  src/control/PrintReportControl.java
  src/entity/Character.java
  src/entity/CharacterList.java
  src/entity/Child.java
  src/entity/CommonInfect.java
  src/entity/Game.java
  src/entity/Match.java
  src/entity/Report.java
  src/entity/Soldier.java
  src/entity/Survivor.java
  src/entity/Tank.java
  src/entity/Teacher.java
  src/entity/Zombie.java
Labels: enhancement

#25 Added in initial list Character counts/printout
  src/control/PlayMatchControl.java
Labels: enhancement

#26 Enhance report for when there are 0 survivors
  src/entity/Report.java
Labels: enhancement

#28 Added ID to Character/Changed ID algo in death print
  src/entity/Character.java
  src/entity/CharacterList.java
  src/entity/Child.java
  src/entity/CommonInfect.java
  src/entity/Match.java
  src/entity/Soldier.java
  src/entity/Survivor.java
  src/entity/Tank.java
  src/entity/Teacher.java
  src/entity/Zombie.java
Labels: enhancement

#30 Devin/#23 - Add Character ID's and death printout to version2
  src/control/PrintReportControl.java
  src/entity/Character.java
  src/entity/CharacterList.java
  src/entity/Child.java
  src/entity/CommonInfect.java
  src/entity/Match.java
  src/entity/Soldier.java
  src/entity/Survivor.java
  src/entity/Tank.java
  src/entity/Teacher.java
  src/entity/Zombie.java
Labels: enhancement

#29 Version 2 Release!
  src/control/PlayMatchControl.java
  src/control/PrintReportControl.java
  src/entity/Character.java
  src/entity/CharacterList.java
  src/entity/Child.java
  src/entity/CommonInfect.java
  src/entity/Match.java
  src/entity/Report.java
  src/entity/Soldier.java
  src/entity/Survivor.java
  src/entity/Tank.java
  src/entity/Teacher.java
  src/entity/Zombie.java
Labels: enhancement

#36 Added in Survivor Class Weapon functionality
  src/entity/Character.java
  src/entity/Child.java
  src/entity/Soldier.java
  src/entity/Survivor.java
  src/entity/Teacher.java
Labels: enhancement

#38 Added Weapon superclass and subclasses. #31
  src/entity/AssaultRifle.java
  src/entity/Axe.java
  src/entity/Crowbar.java
  src/entity/FryingPan.java
  src/entity/Pistol.java
  src/entity/Shotgun.java
  src/entity/SubmachineGun.java
  src/entity/Weapon.java
Labels: enhancement

#42 Release 3.0
  src/entity/AssaultRifle.java
  src/entity/Axe.java
  src/entity/Character.java
  src/entity/CharacterList.java
  src/entity/Child.java
  src/entity/Crowbar.java
  src/entity/FryingPan.java
  src/entity/Match.java
  src/entity/Pistol.java
  src/entity/Shotgun.java
  src/entity/Soldier.java
  src/entity/SubmachineGun.java
  src/entity/Survivor.java
  src/entity/Teacher.java
  src/entity/Weapon.java
Labels: enhancement, testing
